// "il mondo dorme" — composition data, mirroring configs/PGE_test.yml structure.
// 5 streams, 60s timeline.
window.PGE_DATA = {
  project: "PGE_test",
  title: "il mondo dorme",
  duration: 60,
  bpm: 120,
  streams: [
    {
      id: "stream1", onset: 0.0, duration: 5.0, sample: "pino.wav",
      color: "#5C8868", mute: false, solo: false,
      timeMode: "normalized", distributionMode: "gaussian",
      density: null, densityEnv: [[0,10],[15,10],[40,50],[60,30],[100,30]],
      distribution: null, distributionEnv: [[0,0],[50,1],[100,0]],
      volume: -6.0, volumeRange: 0,
      pan: 0, panRange: 0,
      grain: { duration: null, durationEnv: [[0,0.05],[50,0.08],[100,0.05]], durationRange: 0.01, envelope: "hanning" },
      pointer: { start: 0, speedRatio: null, speedRatioEnv: [[0,-1],[100,1]], loopStart: null, loopDur: null },
      pitch: { semitones: 0, range: 0 },
      voices: { num: 1 },
      dephase: { type: "cubic", points: [[0,50],[50,0],[100,30]] },
    },
    {
      id: "stream2", onset: 40.0, duration: 5.0, sample: "pino.wav",
      color: "#B89241", mute: false, solo: false,
      timeMode: "absolute", distributionMode: "uniform",
      density: 12, distribution: 0.0,
      volume: -6.0, volumeRange: 0,
      pan: 0, panRange: 0,
      grain: { duration: 0.05, durationRange: 0, envelope: "hanning" },
      pointer: { start: 0, speedRatio: 1.0, loopStart: null, loopDur: null },
      pitch: { semitones: 0, range: 0 },
      voices: { num: 1 },
    },
    {
      id: "stream3", onset: 30.0, duration: 5.0, sample: "pino.wav",
      color: "#3F8884", mute: false, solo: false,
      timeMode: "absolute", distributionMode: "uniform",
      density: 12, distribution: 0.0,
      volume: -6.0, volumeRange: 0,
      pan: 0, panRange: 0,
      grain: { duration: 0.05, durationRange: 0, envelope: "hanning" },
      pointer: { start: 0, speedRatio: 1.0, loopStart: null, loopDur: null },
      pitch: { semitones: 0, range: 0 },
      voices: { num: 1 },
    },
    {
      id: "stream4", onset: 20.0, duration: 5.0, sample: "pino.wav",
      color: "#5965A8", mute: false, solo: false,
      timeMode: "absolute", distributionMode: "uniform",
      density: 12, distribution: 0.0,
      volume: -6.0, volumeRange: 0,
      pan: 0, panRange: 0,
      grain: { duration: 0.05, durationRange: 0, envelope: "hanning" },
      pointer: { start: 0, speedRatio: 1.0, loopStart: null, loopDur: null },
      pitch: { semitones: 0, range: 0 },
      voices: { num: 1 },
    },
    {
      id: "stream5", onset: 0.0, duration: 10.0, sample: "001-0-27_9.wav",
      color: "#8E5F8E", mute: false, solo: false,
      timeMode: "normalized", distributionMode: "gaussian",
      density: 3, distribution: null, distributionEnv: [[0,0],[50,1],[100,0]],
      volume: -9.0, volumeRange: 0,
      pan: null, panEnv: [[0,-3600],[100,3600]], panRange: 0,
      grain: { duration: 0.05, durationRange: 0, envelope: "gaussian" },
      pointer: { start: 0, speedRatio: 1.0, loopStart: null, loopDur: null },
      pitch: { semitones: 0, range: 0 },
      voices: { num: 1 },
    },
  ],
  samples: [
    { name: "pino.wav", duration: 3.402 },
    { name: "001-0-27_9.wav", duration: 9.180 },
    { name: "drum_loop.wav", duration: 2.000 },
    { name: "sweep_long.wav", duration: 12.500 },
    { name: "rain_field.wav", duration: 8.320 },
    { name: "voice_a.wav", duration: 5.100 },
  ],
};
